### ISSUE TITLE
npm installation without cairo

### ISSUE THREAD

**Issue by brendangibson** [jasondavies/d3-cloud#70]
Is it possible to install d3.layout.cloud without installing cairo?

As I understand, cairo would be used for server-side canvas rendering, which I don't need to do.  Having to install cairo on all of my deployment boxes is something that I'd like to avoid doing.

Here are the errors I get when attempting to install d3.layout.cloud - 

```
$ npm install d3.layout.cloud
-
> canvas@1.2.7 install /Users/bdgibson/dev/bikini/node_modules/d3.layout.cloud/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:343:16)
gyp ERR! stack     at ChildProcess.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:820:12)
gyp ERR! System Darwin 14.1.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/bdgibson/dev/bikini/node_modules/d3.layout.cloud/node_modules/canvas
gyp ERR! node -v v0.10.35
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok 

npm ERR! canvas@1.2.7 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.2.7 install script.
npm ERR! This is most likely a problem with the canvas package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls canvas
npm ERR! There is likely additional logging output above.
npm ERR! System Darwin 14.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "d3.layout.cloud"
npm ERR! cwd /Users/bdgibson/dev/bikini
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0
```

**Comment by jasondavies** [comment]
I'm assuming this is because you're using npm to install packages for browser consumption rather than for node?

**Comment by brendangibson** [comment]
@jasondavies Yes. That's right. This application is purely client-side.

**Comment by cesine** [comment]
we had the same problem for one of our intern's computer which was a windows machine.

we too are using browserify to build, so we also use npm to manage client side deps. 

our solution was to put `canvas` as an optional dependancy. https://github.com/iLanguage/d3-cloud/blob/master/package.json#L29 which kind of works in that you can use it in browserify, and if you are truly working server side, you can manage the canvas install yourself. 

I'll submit this as a pr and see if it anyone else needs canvas to be optional.

**Comment by rus0000** [comment]
+1
